from PIL import Image,ImageFilter,ImageChops,ImageEnhance#导入Image模块
img1=Image.open('img1.jpg')#打开图片
img1.show()#显示图片
print('图片的格式',img1.format,'\n大小',img1.size,'\n宽度',img1.width,'高度',img1.height,'\n获取(100,100)处RGB值',img1.getpixel((100,100)))#查看图片信息
#=======================================================================================
img2=Image.new('RGB',img1.size,'blue')#创建RGB模式蓝色图片,大小和img1一样
Image.blend(img1,img2,alpha=0.5).show()#透明度混合
img3=Image.open('img3.jpg').resize(img1.size)#重设img3大小,和img1一样
r,g,b=img3.split()#按RGB三个通道切割
Image.composite(img1,img3,b).show()#使用b通道对img1遮罩
#=======================================================================================
Image.eval(img1,lambda x:x*2).show()#每个像素扩大2倍,使用匿名函数,将img1中每个像素传给x,x*2返回
img4=img1.copy()#复制图像
img4.thumbnail((920,200))#按尺寸进行缩放
img4.show()
img3_crop=img3.crop((50,50,200,200))#剪切矩形区域
img4.paste(img3_crop,(30,30))#粘贴到指定位置
img4.show()
#=======================================================================================
img1.rotate(30).show()#旋转图像
img1.transpose(Image.FLIP_LEFT_RIGHT).show()#左右镜像反转
img1.transpose(Image.ROTATE_90).show()#90°旋转
img1.transpose(Image.TRANSPOSE).show()#转置
r1,g1,b1=img2.split()#按照RGB通道分离图像
r2,g2,b2=img3.split()
Image.merge('RGB',[r1,g2,b2]).show()#按照RGB通道合并图像
#=======================================================================================
img_output=Image.new('RGB',(2*img3.width,img3.height))#创建一个2倍img3宽的画布
img_output.paste(img3,(0,0))#将img3粘贴在左上角
img_filter1=img3.filter(ImageFilter.GaussianBlur)#高斯滤镜
img_filter2=img3.filter(ImageFilter.CONTOUR)#轮廓滤镜
img_filter3=img3.filter(ImageFilter.EMBOSS)#浮雕滤镜
filters=[]#创建列表
filters.append(img_filter1)
filters.append(img_filter2)
filters.append(img_filter3)
for img_filter in filters:#循环比对三种滤镜
    img_output.paste(img_filter,(img3.width,0))#将带滤镜的图像放在右侧方便对比
    img_output.show()
#=======================================================================================
ImageChops.add(img1,img3).show()#对两张图片进行算数加法
ImageChops.darker(img1,img3).show()#取两张图片中对应像素的较小值
ImageChops.multiply(img1,img3).show()#两张图片互相叠加
ImageChops.screen(img1,img3).show()#投影
ImageChops.invert(img1).show()#反色函数,底片效果
ImageChops.difference(img1,img3).show()#比较差异
#=======================================================================================
img_output=Image.new('RGB',(3*img3.width,img3.height))#创建一个3倍img3宽的画布
img_output.paste(ImageEnhance.Color(img3).enhance(2),(0,0))#获取色彩调整器,色彩增强2倍,将图片粘贴在左上角
img_output.paste(ImageEnhance.Brightness(img3).enhance(0.3),(img3.width,0))#获取亮度调整器,亮度减弱0.3倍,将图片放在右侧方便对比
img_output.paste(img3.point(lambda i:i*1.5),(2*img3.width,0))#对像素点进行1.5倍运算
img_output.show()